### ISSUE TITLE
Set media queries

### ISSUE THREAD

**Issue by Mannuel25** [Topman-14/InfoHub#11]
Define media queries for mobile view in the styles.css file [here](https://github.com/Topman-14/InfoHub/tree/main/src/css)

**Comment by JAILBREAK-101** [comment]
I'd like to try this issue

**Comment by Mannuel25** [comment]
Sure, it'd be assigned to you, once [this](https://github.com/Topman-14/InfoHub/issues/9) has been completed.

**Comment by JAILBREAK-101** [comment]
Is this ready to be worked on now

**Comment by JAILBREAK-101** [comment]
I want to work on it
