### ISSUE TITLE
Style contributors page grid

### ISSUE THREAD

**Issue by Mannuel25** [Topman-14/InfoHub#15]
Check the [design template](https://github.com/Topman-14/InfoHub/blob/main/assets/design%20templates/desktop_view.jpg) for a visual guide.

Style the contributors page in a contributors.css file in the [CSS folder](https://github.com/Topman-14/InfoHub/tree/main/src/css), and link contributors.html to it 🚀.

**Comment by Lloyd-the-dev** [comment]
I'll like to try this

**Comment by Mannuel25** [comment]
Hello @Lloyd-the-god , any progress on this?
