### ISSUE TITLE
Generate Favicons

### ISSUE THREAD

**Issue by Mannuel25** [Topman-14/InfoHub#16]
- Using this [file](https://github.com/Topman-14/InfoHub/blob/main/assets/Infohub-logo.jpg), generate the various favicons.
- Use this [site](https://www.favicon-generator.org/) to generate the favicons.
- Create a separate folder called `favicons` inside the assets folder, then add the generated favicons there.

**Comment by 786-aquib** [comment]
Hey I want to fix it..
i want to contribute here
