### ISSUE TITLE
Add favicon links in all pages

### ISSUE THREAD

**Issue by Topman-14** [Topman-14/InfoHub#31]
## Add favicon links to each web page, and ensure the favicon displays correctly in the web browser
The favicons are in the assets folder [here](https://github.com/Topman-14/InfoHub/tree/main/assets)

Only work on html documents in the html directory in [src](https://github.com/Topman-14/InfoHub/tree/main/src)

**Comment by Yashdon999** [comment]
i would like to work on this issue

**Comment by imanmachukwu** [comment]
Hey, I would love to work on this issue.

**Comment by Topman-14** [comment]
Cool🚀. When you're done, make a pull request to the dev branch, not main. Happy coding!

**Comment by MOHDNEHALKHAN** [comment]
In your project there is only three html pages and I see that there are many favicon icons in favicon section , so we have to check every icon on each webpage  and whatever look good we have to add it.

**Comment by Mannuel25** [comment]
> Hey, I would love to work on this issue.

Hello @imanmachukwu , still working on this?
