### ISSUE TITLE
Style homepage grid

### ISSUE THREAD

**Issue by Mannuel25** [Topman-14/InfoHub#9]
Check the <a href="https://github.com/Topman-14/InfoHub/blob/main/assets/design%20templates/desktop_view.jpg">design template</a> before making changes.

The homepage has a "Top picks" grid, style accordingly. All styles for the homepage should be done in the home.css file in the CSS folder [here ](https://github.com/Topman-14/InfoHub/tree/main/src/css).

The images in the "Top picks" grid are there for illustrative purposes. Instead of those images, create a skeleton placeholder

The styles.css folder contains the global CSS variables.

**Comment by JAILBREAK-101** [comment]
I would like to work on this issue
